controllers/MemberController.php
<?php

namespace app\controllers;

use app\models\Role;
use yii\web\Controller;
use Yii;
use app\models\Member;
use yii\helpers\Url;
use app\helpers\MyHelper;
use yii\data\Pagination;
use app\models\Image;
use app\models\JoinTeam;
use yii\web\UploadedFile;

Yii::$app->assetManager->bundles['yii\\bootstrap\\BootstrapAsset'] = [
    'css' => [],
    'js' => []
];

class MemberController extends Controller
{
    public $img_slides = '';
    public $defaultAction = 'all-members';
    private $pageSize = 40;


    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'successCallback'],
            ],
        ];
    }

    public function successCallback($client)
    {
        $attributes = $client->getUserAttributes();
        $email = $attributes['emails'][0]['value'];
        $name = isset($attributes['displayName']) ? $attributes['displayName'] : "";
        $member = Member::checkMember($email, $name);
        $member->login(3600 * 24 * 30);

        Yii::$app->session['email'] = $email;
        Yii::$app->session['name'] = $name;
        $member = Member::findByEmail($email);
        Yii::$app->session['id'] = $member->id;
        Yii::$app->session['role_id'] = $member->role_id;
        if (empty(Yii::$app->authManager->getRolesByUser($member->id))) {
            $roleName = Role::findOne($member->role_id)['name'];
            $role = Yii::$app->authManager->getRole($roleName);
            Yii::$app->authManager->assign($role, $member->id);
        }
        $this->redirect(Url::to(['/member/all-members']));
    }


    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest && $action->id != 'login')
            $this->redirect(Url::to(['/member/login']));
        $this->img_slides = Image::find()->asArray()->where(['member_id' => '-1'])->all();



        return parent::beforeAction($action);
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->getIsGuest()) {
            $this->redirect(Url::to(['member/all-members']));
        }
        $model = new Member();
        return $this->render('login', ['model' => $model, 'img_slides' => $this->img_slides]);
    }

    public function actionAllMembers()
    {

        $pagination = new Pagination(['pageSize' => $this->pageSize]);
        if (Yii::$app->request->post('find')) {
            $name = Yii::$app->request->post('find');
            $members = Member::find()->asArray()->select(['id', 'name', 'phone', 'birthday', 'avatar'])->where(['like', 'name', $name])->orderBy('birthday,name');
        } else {
            $members = Member::find()->asArray()->select(['id', 'name', 'phone', 'birthday', 'avatar'])->orderBy('birthday,name');
        }
        if ($members->count() > 0) {
            $pagination->totalCount = $members->count();
            $members1 = $members->asArray()->offset($pagination->offset)->limit($pagination->limit)->all();
            return $this->render('list_member', ['members' => $members1, 'pagination' => $pagination, 'find' => '1', 'img_slides' => $this->img_slides, 'title' => 'All Members']);
        } else
            return $this->render('list_member', ['find' => '1', 'img_slides' => $this->img_slides, 'title' => 'All Members']);
    }

    public function actionOlderMembers()
    {
        $pagination = new Pagination(['pageSize' => $this->pageSize]);
        if ($birthday = Yii::$app->user->identity->birthday) {
            $members = Member::find()->asArray()->select(['id', 'name', 'phone', 'birthday', 'avatar'])->andWhere(['<', 'birthday', Yii::$app->user->identity->birthday])->andWhere(['not like', 'birthday', MyHelper::getYear($birthday)])->orderBy('birthday,name');
            if ($members->count() > 0) {
                $pagination->totalCount = $members->count();
                $members1 = $members->asArray()->offset($pagination->offset)->limit($pagination->limit)->all();
                return $this->render('list_member', ['members' => $members1, 'pagination' => $pagination, 'img_slides' => $this->img_slides, 'title' => 'Older Members']);
            }
        }
        return $this->render('list_member', ['img_slides' => $this->img_slides, 'title' => 'Older Members']);
    }

    public function actionMembersOfTheSameAge()
    {
        $pagination = new Pagination(['pageSize' => $this->pageSize]);
        if ($birthday = Yii::$app->user->identity->birthday) {
            $members = Member::find()->asArray()->select(['name', 'phone', 'birthday', 'avatar', 'id'])->andWhere(['like', 'birthday', MyHelper::getYear($birthday)])->andWhere(['<>', 'id', Yii::$app->user->id])->orderBy('birthday,name');
            if ($members->count() > 0) {
                $pagination->totalCount = $members->count();
                $members1 = $members->asArray()->offset($pagination->offset)->limit($pagination->limit)->all();
                return $this->render('list_member', ['members' => $members1, 'pagination' => $pagination, 'img_slides' => $this->img_slides, 'title' => 'Members of the same age']);
            }
        }
        return $this->render('list_member', ['img_slides' => $this->img_slides, 'title' => 'Members of the same age']);
    }

    public function actionYoungerMembers()
    {
        $pagination = new Pagination(['pageSize' => $this->pageSize]);
        if ($birthday = Yii::$app->user->identity->birthday) {
            $members = Member::find()->asArray()->select(['name', 'phone', 'birthday', 'avatar', 'id'])->andWhere(['>', 'birthday', Yii::$app->user->identity->birthday])->andWhere(['not like', 'birthday', MyHelper::getYear($birthday)])->orderBy('birthday,name');
            if ($members->count() > 0) {
                $pagination->totalCount = $members->count();
                $members1 = $members->asArray()->offset($pagination->offset)->limit($pagination->limit)->all();
                return $this->render('list_member', ['members' => $members1, 'pagination' => $pagination, 'img_slides' => $this->img_slides, 'title' => 'Younger Members']);
            }
        }

        return $this->render('list_member', ['img_slides' => $this->img_slides, 'title' => 'Younger Members']);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        $this->redirect(['/member/login']);
    }

    public function actionJoinTeam($team_id)
    {
        $member_id = Yii::$app->user->id;
        $join_team = JoinTeam::findOne(['member_id' => $member_id, 'team_id' => $team_id]);
        if ($join_team == null) {
            $join_team = new JoinTeam();
            $join_team->member_id = $member_id;
            $join_team->team_id = $team_id;
            $join_team->active = 0;
            $join_team->save();
        } else {
            if ($join_team->active != 1)
                $join_team->active = 0;
            $join_team->save();
        }
        $this->redirect(['/team/team']);
    }


    public function actionLeaveTeam($team_id)
    {
        $member_id = Yii::$app->user->id;
        $join_team = JoinTeam::findOne(['member_id' => $member_id, 'team_id' => $team_id]);
        $join_team->active = -1;
        $join_team->save();
        $this->redirect(['/team/team']);

    }

    public function actionUpload()
    {

        $model = new Image();
        if ($model->load(Yii::$app->request->post())) {
            $model->crop_info = $model->image;
            $model->image = UploadedFile::getInstance($model, 'image');
            $model->image->saveAs('web/img/' . $model->crop_info . '-' . date('_Y_m_d_h_i_s_a') . '.' . $model->image->extension);
            $name = $model->image = $model->crop_info . '-' . date('_Y_m_d_h_i_s_a') . '.' . $model->image->extension;
            $model->member_id = Yii::$app->user->id;
            if (!$model->save(false)) {
                echo 'Error!';
                usleep('5000000');
            } else {
                if ($model->is_avatar) {
                    $member = Member::findOne(['id' => Yii::$app->user->id]);
                    $member->avatar = $name;
                    $member->save(false);
                }
                $this->redirect(['/profile/my-profile']);
            }
        }
        return $this->render('upload', ['model' => $model, 'img_slides' => $this->img_slides]);
    }

    public function actionDeleteImg($image)
    {
        $img = Image::findOne(['image' => $image]);
        if ($img) {
            $img->delete();
            if (file_exists(Yii::getAlias('@web/web/img/' . $image)))
                unlink(Yii::getAlias('@web/web/img/' . $image));
        }

        $member = Member::findOne(['id' => Yii::$app->user->id]);
        if ($member->avatar == $image) {
            $member->avatar = '';
            $member->save(false);
        }
        $this->redirect(['/profile/my-profile']);
    }


}

controllers/TeamController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use Yii;
use app\models\Team;
use app\models\Image;
use yii\helpers\Url;
use app\models\JoinTeam;

Yii::$app->assetManager->bundles['yii\\bootstrap\\BootstrapAsset'] = [
    'css' => [],
    'js' => []
];


class TeamController extends Controller
{
    public $img_slides = '';
    public $layout = 'layout';

    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest)
            $this->redirect(Url::to(['/member/login']));
        $this->img_slides = Image::find()->asArray()->where(['member_id' => '-1'])->all();
        return parent::beforeAction($action);
    }

    public function actionTeam($team_id = -1)
    {
        $model = Team::find()->asArray()->orderBy('team.name')->all();
        if ($model && $team_id == -1) {
            $team_id = $model[0]['id'];
        }
        $jointeam = JoinTeam::findOne(['member_id' => Yii::$app->user->id, 'team_id' => $team_id]);
        if ($jointeam != null)
            $join = 0;
        else $join = 1;
        $leaveteam = JoinTeam::findOne(['member_id' => Yii::$app->user->id, 'team_id' => $team_id, 'active' => '1']);
        if ($leaveteam == null)
            $leave = 0;
        else $leave = 1;
        $members = Yii::$app->db->createCommand('select team.id as team_id,team.name as team_name,team.desc,member.name,member.birthday,member.sex,member.phone,member.avatar,member.id,join_team.active from team left join join_team on team.id=join_team.team_id left join member on join_team.member_id=member.id where  team.id=:team_id order by member.birthday', [':team_id' => $team_id])->queryAll();
        return $this->render('list_team', ['list_team' => $model, 'members' => $members, 'img_slides' => $this->img_slides,'leave'=>$leave,'join'=>$join]);
    }


}

views/layouts/layout.php
<?php

use app\assets\LayoutAsset;
use yii\helpers\Url;

LayoutAsset::register($this);
if (class_exists('yii\debug\Module')) {
    $this->off(\yii\web\View::EVENT_END_BODY, [\yii\debug\Module::getInstance(), 'renderToolbar']);
}
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <link rel="icon" type="image/x-icon" href=<?= Yii::getAlias('@web/web/images/short_icon.png') ?>>
    <?php $this->head(); ?>
</head>
<body>
<?php $this->beginBody(); ?>
<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
    your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to
    improve your experience.</p>
<![endif]-->


<div class="bg-overlay"></div>

<div class="container-fluid">
    <div class="row">

        <div class="col-md-4 col-sm-12">
            <div class="sidebar-menu">

                <div class="logo-wrapper">
                    <h1 class="logo">
                        <a href="#"><img src=<?= Yii::getAlias('@web/web/images/logo.png') ?>>
                            <span>Kaopiz - Keep Innovating</span></a>
                    </h1>
                </div>
                <!-- /.logo-wrapper -->

                <div class="menu-wrapper">
                    <ul class="menu">
                        <!--  <li><a class="homebutton" href="#">Home</a></li>-->
                        <li><a href=<?= Url::to(['/member/all-members']) ?>>Members</a></li>
                        <li><a href=<?= Url::to(['/team/team']) ?>>Team</a></li>
                        <li><a href=<?= Url::to(['/profile/my-profile']) ?>>My Profile</a></li>

                    </ul>
                    <!-- /.menu -->
                    <a title="Logout" href=<?= Url::to(['/member/logout']) ?> class="toggle-menu"><i
                            class="fa fa-power-off"></i></a>
                </div>
                <!-- /.menu-wrapper -->

                <!--Arrow Navigation-->


            </div>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.col-md-4 -->

        <div class="col-md-8 col-sm-12">
            <?= $content ?>
        </div>

    </div>
</div>

<!-- /.container-fluid -->

<?php $this->endBody() ?>



</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post', ['class' => 'navbar-form'])
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>