models/Team.php
<?php

namespace app\models;

use app\models\JoinTeam;
use Yii;
use app\models\Member;
class Team extends base\Team {

    public function attributeLabels() {
        return [
            'id' => 'ID',
            'name' => 'Tên Team',
            'desc' => 'Mô tả về Team',
        ];
    }

    public function getJoinTeam() {
        return $this->hasMany(JoinTeam::className(), ['team_id' => 'id']);
    }
}

?>

controllers/MemberController.php
<?php

namespace app\controllers;

use app\models\Role;
use yii\web\Controller;
use Yii;
use app\models\Member;
use yii\helpers\Url;
use app\helpers\MyHelper;
use yii\data\Pagination;
use app\models\Image;
use app\models\JoinTeam;
use yii\web\UploadedFile;

Yii::$app->assetManager->bundles['yii\\bootstrap\\BootstrapAsset'] = [
    'css' => [],
    'js' => []
];

class MemberController extends Controller
{
    public $img_slides = '';
    public $defaultAction = 'all-members';
    private $pageSize = 40;


    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'successCallback'],
            ],
        ];
    }

    public function successCallback($client)
    {
        $attributes = $client->getUserAttributes();
        $email = $attributes['emails'][0]['value'];
        $name = isset($attributes['displayName']) ? $attributes['displayName'] : "";
        $member = Member::checkMember($email, $name);
        $member->login(3600 * 24 * 30);

        Yii::$app->session['email'] = $email;
        Yii::$app->session['name'] = $name;
        $member = Member::findByEmail($email);
        Yii::$app->session['id'] = $member->id;
        Yii::$app->session['role_id'] = $member->role_id;
        if (empty(Yii::$app->authManager->getRolesByUser($member->id))) {
            $roleName = Role::findOne($member->role_id)['name'];
            $role = Yii::$app->authManager->getRole($roleName);
            Yii::$app->authManager->assign($role, $member->id);
        }
        $this->redirect(Url::to(['/member/all-members']));
    }


    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest && $action->id != 'login')
            $this->redirect(Url::to(['/member/login']));
        $this->img_slides = Image::find()->asArray()->where(['member_id' => '-1'])->all();



        return parent::beforeAction($action);
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->getIsGuest()) {
            $this->redirect(Url::to(['member/all-members']));
        }
        $model = new Member();
        return $this->render('login', ['model' => $model, 'img_slides' => $this->img_slides]);
    }

    public function actionAllMembers()
    {

        $pagination = new Pagination(['pageSize' => $this->pageSize]);
        if (Yii::$app->request->post('find')) {
            $name = Yii::$app->request->post('find');
            $members = Member::find()->asArray()->select(['id', 'name', 'phone', 'birthday', 'avatar'])->where(['like', 'name', $name])->orderBy('birthday,name');
        } else {
            $members = Member::find()->asArray()->select(['id', 'name', 'phone', 'birthday', 'avatar'])->orderBy('birthday,name');
        }
        if ($members->count() > 0) {
            $pagination->totalCount = $members->count();
            $members1 = $members->asArray()->offset($pagination->offset)->limit($pagination->limit)->all();
            return $this->render('list_member', ['members' => $members1, 'pagination' => $pagination, 'find' => '1', 'img_slides' => $this->img_slides, 'title' => 'All Members']);
        } else
            return $this->render('list_member', ['find' => '1', 'img_slides' => $this->img_slides, 'title' => 'All Members']);
    }

    public function actionOlderMembers()
    {
        $pagination = new Pagination(['pageSize' => $this->pageSize]);
        if ($birthday = Yii::$app->user->identity->birthday) {
            $members = Member::find()->asArray()->select(['id', 'name', 'phone', 'birthday', 'avatar'])->andWhere(['<', 'birthday', Yii::$app->user->identity->birthday])->andWhere(['not like', 'birthday', MyHelper::getYear($birthday)])->orderBy('birthday,name');
            if ($members->count() > 0) {
                $pagination->totalCount = $members->count();
                $members1 = $members->asArray()->offset($pagination->offset)->limit($pagination->limit)->all();
                return $this->render('list_member', ['members' => $members1, 'pagination' => $pagination, 'img_slides' => $this->img_slides, 'title' => 'Older Members']);
            }
        }
        return $this->render('list_member', ['img_slides' => $this->img_slides, 'title' => 'Older Members']);
    }

    public function actionMembersOfTheSameAge()
    {
        $pagination = new Pagination(['pageSize' => $this->pageSize]);
        if ($birthday = Yii::$app->user->identity->birthday) {
            $members = Member::find()->asArray()->select(['name', 'phone', 'birthday', 'avatar', 'id'])->andWhere(['like', 'birthday', MyHelper::getYear($birthday)])->andWhere(['<>', 'id', Yii::$app->user->id])->orderBy('birthday,name');
            if ($members->count() > 0) {
                $pagination->totalCount = $members->count();
                $members1 = $members->asArray()->offset($pagination->offset)->limit($pagination->limit)->all();
                return $this->render('list_member', ['members' => $members1, 'pagination' => $pagination, 'img_slides' => $this->img_slides, 'title' => 'Members of the same age']);
            }
        }
        return $this->render('list_member', ['img_slides' => $this->img_slides, 'title' => 'Members of the same age']);
    }

    public function actionYoungerMembers()
    {
        $pagination = new Pagination(['pageSize' => $this->pageSize]);
        if ($birthday = Yii::$app->user->identity->birthday) {
            $members = Member::find()->asArray()->select(['name', 'phone', 'birthday', 'avatar', 'id'])->andWhere(['>', 'birthday', Yii::$app->user->identity->birthday])->andWhere(['not like', 'birthday', MyHelper::getYear($birthday)])->orderBy('birthday,name');
            if ($members->count() > 0) {
                $pagination->totalCount = $members->count();
                $members1 = $members->asArray()->offset($pagination->offset)->limit($pagination->limit)->all();
                return $this->render('list_member', ['members' => $members1, 'pagination' => $pagination, 'img_slides' => $this->img_slides, 'title' => 'Younger Members']);
            }
        }

        return $this->render('list_member', ['img_slides' => $this->img_slides, 'title' => 'Younger Members']);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        $this->redirect(['/member/login']);
    }

    public function actionJoinTeam($team_id)
    {
        $member_id = Yii::$app->user->id;
        $join_team = JoinTeam::findOne(['member_id' => $member_id, 'team_id' => $team_id]);
        if ($join_team == null) {
            $join_team = new JoinTeam();
            $join_team->member_id = $member_id;
            $join_team->team_id = $team_id;
            $join_team->active = 0;
            $join_team->save();
        } else {
            if ($join_team->active != 1)
                $join_team->active = 0;
            $join_team->save();
        }
        $this->redirect(['/team/team']);
    }


    public function actionLeaveTeam($team_id)
    {
        $member_id = Yii::$app->user->id;
        $join_team = JoinTeam::findOne(['member_id' => $member_id, 'team_id' => $team_id]);
        $join_team->active = -1;
        $join_team->save();
        $this->redirect(['/team/team']);

    }

    public function actionUpload()
    {

        $model = new Image();
        if ($model->load(Yii::$app->request->post())) {
            $model->crop_info = $model->image;
            $model->image = UploadedFile::getInstance($model, 'image');
            $model->image->saveAs('web/img/' . $model->crop_info . '-' . date('_Y_m_d_h_i_s_a') . '.' . $model->image->extension);
            $name = $model->image = $model->crop_info . '-' . date('_Y_m_d_h_i_s_a') . '.' . $model->image->extension;
            $model->member_id = Yii::$app->user->id;
            if (!$model->save(false)) {
                echo 'Error!';
                usleep('5000000');
            } else {
                if ($model->is_avatar) {
                    $member = Member::findOne(['id' => Yii::$app->user->id]);
                    $member->avatar = $name;
                    $member->save(false);
                }
                $this->redirect(['/profile/my-profile']);
            }
        }
        return $this->render('upload', ['model' => $model, 'img_slides' => $this->img_slides]);
    }

    public function actionDeleteImg($image)
    {
        $img = Image::findOne(['image' => $image]);
        if ($img) {
            $img->delete();
            if (file_exists(Yii::getAlias('@web/web/img/' . $image)))
                unlink(Yii::getAlias('@web/web/img/' . $image));
        }

        $member = Member::findOne(['id' => Yii::$app->user->id]);
        if ($member->avatar == $image) {
            $member->avatar = '';
            $member->save(false);
        }
        $this->redirect(['/profile/my-profile']);
    }


}

controllers/ProfileController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use Yii;
use app\models\Member;
use app\models\Image;

Yii::$app->assetManager->bundles['yii\\bootstrap\\BootstrapAsset'] = [
    'css' => [],
    'js' => []
];

class ProfileController extends Controller
{
    public $img_slides = '';
    public $layout = 'layout';

    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest)
            $this->redirect(['/member/login']);
        $this->img_slides = Image::find()->asArray()->where(['member_id' => '-1'])->all();
        return parent::beforeAction($action);
    }

    public function actionMyProfile()
    {
        $model = Member::findById(Yii::$app->user->id);
        $list_img = Image::find()->select('image')->asArray()->where(['member_id' => Yii::$app->user->id])->all();
        if ($model->load(Yii::$app->request->post(), "Member")) {
            $model->save(false);
        }
        return $this->render('my_profile', ['model' => $model, 'list_img' => $list_img, 'img_slides' => $this->img_slides]);
    }

    public function actionMemberProfile($member_id)
    {
        $model = Member::findById($member_id);
        $list_img = Image::find()->select('image')->asArray()->where(['member_id' => $member_id])->all();
        if (Yii::$app->user->can('editOwnProfile', ['member' => $model]))
            $this->redirect(['profile/my-profile']);
        if (Yii::$app->user->can('editProfile')) {
            if ($model->load(Yii::$app->request->post(), "Member")) {
                $model->save();
            }
            return $this->render('member_profile_admin', ['model' => $model, 'img_slides' => $this->img_slides, 'list_img' => $list_img]);
        }
        $data = Member::findById($member_id);
        return $this->render('member_profile', ['data' => $data, 'img_slides' => $this->img_slides, 'list_img' => $list_img]);
    }

}

controllers/TeamController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use Yii;
use app\models\Team;
use app\models\Image;
use yii\helpers\Url;
use app\models\JoinTeam;

Yii::$app->assetManager->bundles['yii\\bootstrap\\BootstrapAsset'] = [
    'css' => [],
    'js' => []
];


class TeamController extends Controller
{
    public $img_slides = '';
    public $layout = 'layout';

    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest)
            $this->redirect(Url::to(['/member/login']));
        $this->img_slides = Image::find()->asArray()->where(['member_id' => '-1'])->all();
        return parent::beforeAction($action);
    }

    public function actionTeam($team_id = -1)
    {
        $model = Team::find()->asArray()->orderBy('team.name')->all();
        if ($model && $team_id == -1) {
            $team_id = $model[0]['id'];
        }
        $jointeam = JoinTeam::findOne(['member_id' => Yii::$app->user->id, 'team_id' => $team_id]);
        if ($jointeam != null)
            $join = 0;
        else $join = 1;
        $leaveteam = JoinTeam::findOne(['member_id' => Yii::$app->user->id, 'team_id' => $team_id, 'active' => '1']);
        if ($leaveteam == null)
            $leave = 0;
        else $leave = 1;
        $members = Yii::$app->db->createCommand('select team.id as team_id,team.name as team_name,team.desc,member.name,member.birthday,member.sex,member.phone,member.avatar,member.id,join_team.active from team left join join_team on team.id=join_team.team_id left join member on join_team.member_id=member.id where  team.id=:team_id order by member.birthday', [':team_id' => $team_id])->queryAll();
        return $this->render('list_team', ['list_team' => $model, 'members' => $members, 'img_slides' => $this->img_slides,'leave'=>$leave,'join'=>$join]);
    }


}

views/team/list_team.php
<?php


use yii\helpers\Url;
use app\helpers\MyHelper;


?>
<title><?= $members[0]['team_name'] ?></title>
<div class="about content">
    <?php if ($list_team) { ?>
        <div class="row">
            <ul class="tabs">
                <?php foreach ($list_team as $team1): ?>
                    <li class="col-md-3 col-sm-3">
                        <a href=<?= Url::to(['/team/team', 'team_id' => $team1['id']]) ?> class="icon-item <?php if ($members[0]['team_id'] == $team1['id']) echo 'active'; ?>
                        ">
                        <b style="font-size:15px"><?= $team1['name'] ?></b>
                        </a> <!-- /.icon-item -->
                    </li>
                <?php endforeach; ?>
            </ul>
            <!-- /.tabs -->
            <div class="col-md-12 col-sm-12">
                <div id="tab4">
                    <div class="toggle-content text-center">
                        <h3>Decription</h3>

                        <p><?= $members[0]['desc'] ? $members[0]['desc'] : NONE ?></p>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-md-5 col-sm-5"></div>
                <div class="col-md-2 col-sm-2"><?php if ($join) { ?>
                        <div style="margin-top:30px"><a
                            href=<?= Url::to(['/member/join-team', 'team_id' => $members[0]['team_id']]) ?> class="jointeam">Join
                            Team</a></div><?php } ?>
                    <?php if ($leave) { ?>
                        <div style="margin-top:30px"><a
                            href=<?= Url::to(['/member/leave-team', 'team_id' => $members[0]['team_id']]) ?> class="jointeam">Leave
                            Team</a></div><?php } ?>
                </div>
                <div class="col-md-5 col-sm-5"></div>
            </div>
            <!-- /.col-md-12 -->
        </div>
        <div class="row">
            <?php $i = 0 ?>
            <?php foreach ($members as $member) {
                if ($member['id'] && $member['active'] == 1) {
                    $i = 1; ?>
                    <div class="col-md-3 col-sm-3">
                        <div class="member-item">
                            <div class="thumb">
                                <a href=<?= Url::to(['profile/member-profile', 'member_id' => $member['id']]) ?>>
                                    <img
                                        src=<?php if (empty($member['avatar'])) echo Yii::getAlias('@web/web/images/base_avatar.jpg');
                                    else echo Yii::getAlias('@web/web/img/' . $member['avatar']);
                                    ?>></a>
                            </div>
                            <h4><?= $member['name'] ? $member['name'] : NONE ?></h4>
                            <span>Age: </span><?php if ($member['birthday']) echo MyHelper::getAge($member['birthday']); else echo NONE; ?>
                            <br>
                            <span>Phone Numbers: </span><?= $member['phone'] ? $member['phone'] : NONE; ?>
                        </div>
                        <!-- /.member-item -->
                    </div>
                <?php }
            }
            ?>

        </div>
    <?php } else echo 'Not found team.' ?>
</div>
<div id="slideshowxx">
    <img class="activexx" src=<?= Yii::getAlias('@web/web/img/' . $img_slides[0]['image']) ?>>
    <?php for ($i = 1; $i < count($img_slides); $i++) { ?>
        <img src=<?= Yii::getAlias('@web/web/img/' . $img_slides[$i]['image']) ?>>
    <?php } ?>
</div>

<script type="text/javascript" src=<?= Yii::getAlias('@web/web/js/vendor/jquery-1.10.1.min.js') ?>></script>
<script type="text/javascript">

    function slideSwitch() {
        var $active = $('#slideshowxx IMG.activexx');

        if ($active.length == 0) $active = $('#slideshowxx IMG:last');

        // use this to pull the images in the order they appear in the markup
        var $next = $active.next().length ? $active.next()
            : $('#slideshowxx IMG:first');

// xóa ghi chú ở 3 dòng bên dưới nếu bạn muốn hiển thị ảnh ngẫu nhiên

        var $sibs = $active.siblings();
        var rndNum = Math.floor(Math.random() * $sibs.length);
        var $next = $($sibs[rndNum]);

        $active.addClass('last-activexx');

        $next.css({opacity: 0.0})
            .addClass('activexx')
            .animate({opacity: 1.0}, 1000, function () {
                $active.removeClass('activexx last-activexx');
            });
    }

    $(function () {
        setInterval("slideSwitch()", 10000);
    });

</script>
<style>
    #slideshowxx {
        position: relative;
        height: 350px;
        z-index: -1;
    }

    #slideshowxx IMG {
        position: absolute;
        top: 0;
        left: 0;
        z-index: 8;
        opacity: 0.0;
    }

    #slideshowxx IMG.activexx {
        z-index: 10;
        opacity: 1.0;
    }

    #slideshowxx IMG.last-activexx {
        z-index: 9;
    }

    #slideshowxx img {
        /* Set rules to fill background */
        min-height: 100%;
        min-width: 1024px;

        /* Set up proportionate scaling */
        width: 100%;
        height: auto;

        /* Set up positioning */
        position: fixed;
        top: 0;
        left: 0;
    }

</style>