models/Member.php
<?php

namespace app\models;

use Yii;

class Member extends base\Member implements \yii\web\IdentityInterface {

    public $username;
    public $password;
    public $authKey;
    public $accessToken;


    public static function checkMember($email, $name) {
        $member = Member::findOne(['email' => $email]);
        if ($member == null) {
            $newMem = new Member();
            $newMem->email = $email;
            $newMem->name = $name;
            $newMem->is_banned = 0;
            $newMem->role_id = Role::getRoleId('member');
            $newMem->save();
            $member = Member::findOne(['email' => $email]);
        }
        return $member;
    }

    public function attributeLabels() {
        return array_merge([
            'id' => '',
            'email' => '',
            'name' => '',
            'sex' => '',
            'avatar' => '',
            'birthday' => '',
            'address' => '',
            'phone' => '',
            'height' => '',
            'weight' => '',
            'country' => '',
            'hobby' => '',
            'forte' => '',
            'foible' => '',
            'nickname' => '',
            'marital' => '',
            'sky' => '',
            'facebook' => '',
            'role_id' => '',
        ]);
    }

    public function rules() {
        $rules = parent::rules();

        //$rules[] = [['sex', 'birthday', 'address', 'phone', 'country'], 'required', 'message' => 'Không được bỏ trống!'];
        return $rules;
    }



    public static function findById($id) {
        return Member::findOne(['id' => $id]);
    }

    public static function findByEmail($email) {
        return Member::findOne(['email' => $email]);
    }

    public static function findIdentity($id) {
        return Member::findOne(['id' => $id]);
    }

    public static function findIdentityByAccessToken($token, $type = null) {
        return static::findOne(['access_token' => $token]);
    }

    public function getId() {
        return $this->id;
    }

    public function getAuthKey() {
        return $this->authKey;
    }

    public function validateAuthKey($authKey) {
        return $this->getAuthKey() == $authKey;
    }

    public function login($duration) {
        if ($this->is_banned == 0) {
            Yii::$app->user->login($this, $duration);
        }
    }

}

?>

controllers/MemberController.php
<?php

namespace app\controllers;

use app\models\Role;
use yii\web\Controller;
use Yii;
use app\models\Member;
use yii\helpers\Url;
use app\helpers\MyHelper;
use yii\data\Pagination;
use app\models\Image;
use app\models\JoinTeam;
use yii\web\UploadedFile;

Yii::$app->assetManager->bundles['yii\\bootstrap\\BootstrapAsset'] = [
    'css' => [],
    'js' => []
];

class MemberController extends Controller
{
    public $img_slides = '';
    public $defaultAction = 'all-members';
    private $pageSize = 40;


    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'successCallback'],
            ],
        ];
    }

    public function successCallback($client)
    {
        $attributes = $client->getUserAttributes();
        $email = $attributes['emails'][0]['value'];
        $name = isset($attributes['displayName']) ? $attributes['displayName'] : "";
        $member = Member::checkMember($email, $name);
        $member->login(3600 * 24 * 30);

        Yii::$app->session['email'] = $email;
        Yii::$app->session['name'] = $name;
        $member = Member::findByEmail($email);
        Yii::$app->session['id'] = $member->id;
        Yii::$app->session['role_id'] = $member->role_id;
        if (empty(Yii::$app->authManager->getRolesByUser($member->id))) {
            $roleName = Role::findOne($member->role_id)['name'];
            $role = Yii::$app->authManager->getRole($roleName);
            Yii::$app->authManager->assign($role, $member->id);
        }
        $this->redirect(Url::to(['/member/all-members']));
    }


    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest && $action->id != 'login')
            $this->redirect(Url::to(['/member/login']));
        $this->img_slides = Image::find()->asArray()->where(['member_id' => '-1'])->all();



        return parent::beforeAction($action);
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->getIsGuest()) {
            $this->redirect(Url::to(['member/all-members']));
        }
        $model = new Member();
        return $this->render('login', ['model' => $model, 'img_slides' => $this->img_slides]);
    }

    public function actionAllMembers()
    {

        $pagination = new Pagination(['pageSize' => $this->pageSize]);
        if (Yii::$app->request->post('find')) {
            $name = Yii::$app->request->post('find');
            $members = Member::find()->asArray()->select(['id', 'name', 'phone', 'birthday', 'avatar'])->where(['like', 'name', $name])->orderBy('birthday,name');
        } else {
            $members = Member::find()->asArray()->select(['id', 'name', 'phone', 'birthday', 'avatar'])->orderBy('birthday,name');
        }
        if ($members->count() > 0) {
            $pagination->totalCount = $members->count();
            $members1 = $members->asArray()->offset($pagination->offset)->limit($pagination->limit)->all();
            return $this->render('list_member', ['members' => $members1, 'pagination' => $pagination, 'find' => '1', 'img_slides' => $this->img_slides, 'title' => 'All Members']);
        } else
            return $this->render('list_member', ['find' => '1', 'img_slides' => $this->img_slides, 'title' => 'All Members']);
    }

    public function actionOlderMembers()
    {
        $pagination = new Pagination(['pageSize' => $this->pageSize]);
        if ($birthday = Yii::$app->user->identity->birthday) {
            $members = Member::find()->asArray()->select(['id', 'name', 'phone', 'birthday', 'avatar'])->andWhere(['<', 'birthday', Yii::$app->user->identity->birthday])->andWhere(['not like', 'birthday', MyHelper::getYear($birthday)])->orderBy('birthday,name');
            if ($members->count() > 0) {
                $pagination->totalCount = $members->count();
                $members1 = $members->asArray()->offset($pagination->offset)->limit($pagination->limit)->all();
                return $this->render('list_member', ['members' => $members1, 'pagination' => $pagination, 'img_slides' => $this->img_slides, 'title' => 'Older Members']);
            }
        }
        return $this->render('list_member', ['img_slides' => $this->img_slides, 'title' => 'Older Members']);
    }

    public function actionMembersOfTheSameAge()
    {
        $pagination = new Pagination(['pageSize' => $this->pageSize]);
        if ($birthday = Yii::$app->user->identity->birthday) {
            $members = Member::find()->asArray()->select(['name', 'phone', 'birthday', 'avatar', 'id'])->andWhere(['like', 'birthday', MyHelper::getYear($birthday)])->andWhere(['<>', 'id', Yii::$app->user->id])->orderBy('birthday,name');
            if ($members->count() > 0) {
                $pagination->totalCount = $members->count();
                $members1 = $members->asArray()->offset($pagination->offset)->limit($pagination->limit)->all();
                return $this->render('list_member', ['members' => $members1, 'pagination' => $pagination, 'img_slides' => $this->img_slides, 'title' => 'Members of the same age']);
            }
        }
        return $this->render('list_member', ['img_slides' => $this->img_slides, 'title' => 'Members of the same age']);
    }

    public function actionYoungerMembers()
    {
        $pagination = new Pagination(['pageSize' => $this->pageSize]);
        if ($birthday = Yii::$app->user->identity->birthday) {
            $members = Member::find()->asArray()->select(['name', 'phone', 'birthday', 'avatar', 'id'])->andWhere(['>', 'birthday', Yii::$app->user->identity->birthday])->andWhere(['not like', 'birthday', MyHelper::getYear($birthday)])->orderBy('birthday,name');
            if ($members->count() > 0) {
                $pagination->totalCount = $members->count();
                $members1 = $members->asArray()->offset($pagination->offset)->limit($pagination->limit)->all();
                return $this->render('list_member', ['members' => $members1, 'pagination' => $pagination, 'img_slides' => $this->img_slides, 'title' => 'Younger Members']);
            }
        }

        return $this->render('list_member', ['img_slides' => $this->img_slides, 'title' => 'Younger Members']);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        $this->redirect(['/member/login']);
    }

    public function actionJoinTeam($team_id)
    {
        $member_id = Yii::$app->user->id;
        $join_team = JoinTeam::findOne(['member_id' => $member_id, 'team_id' => $team_id]);
        if ($join_team == null) {
            $join_team = new JoinTeam();
            $join_team->member_id = $member_id;
            $join_team->team_id = $team_id;
            $join_team->active = 0;
            $join_team->save();
        } else {
            if ($join_team->active != 1)
                $join_team->active = 0;
            $join_team->save();
        }
        $this->redirect(['/team/team']);
    }


    public function actionLeaveTeam($team_id)
    {
        $member_id = Yii::$app->user->id;
        $join_team = JoinTeam::findOne(['member_id' => $member_id, 'team_id' => $team_id]);
        $join_team->active = -1;
        $join_team->save();
        $this->redirect(['/team/team']);

    }

    public function actionUpload()
    {

        $model = new Image();
        if ($model->load(Yii::$app->request->post())) {
            $model->crop_info = $model->image;
            $model->image = UploadedFile::getInstance($model, 'image');
            $model->image->saveAs('web/img/' . $model->crop_info . '-' . date('_Y_m_d_h_i_s_a') . '.' . $model->image->extension);
            $name = $model->image = $model->crop_info . '-' . date('_Y_m_d_h_i_s_a') . '.' . $model->image->extension;
            $model->member_id = Yii::$app->user->id;
            if (!$model->save(false)) {
                echo 'Error!';
                usleep('5000000');
            } else {
                if ($model->is_avatar) {
                    $member = Member::findOne(['id' => Yii::$app->user->id]);
                    $member->avatar = $name;
                    $member->save(false);
                }
                $this->redirect(['/profile/my-profile']);
            }
        }
        return $this->render('upload', ['model' => $model, 'img_slides' => $this->img_slides]);
    }

    public function actionDeleteImg($image)
    {
        $img = Image::findOne(['image' => $image]);
        if ($img) {
            $img->delete();
            if (file_exists(Yii::getAlias('@web/web/img/' . $image)))
                unlink(Yii::getAlias('@web/web/img/' . $image));
        }

        $member = Member::findOne(['id' => Yii::$app->user->id]);
        if ($member->avatar == $image) {
            $member->avatar = '';
            $member->save(false);
        }
        $this->redirect(['/profile/my-profile']);
    }


}

controllers/ProfileController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use Yii;
use app\models\Member;
use app\models\Image;

Yii::$app->assetManager->bundles['yii\\bootstrap\\BootstrapAsset'] = [
    'css' => [],
    'js' => []
];

class ProfileController extends Controller
{
    public $img_slides = '';
    public $layout = 'layout';

    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest)
            $this->redirect(['/member/login']);
        $this->img_slides = Image::find()->asArray()->where(['member_id' => '-1'])->all();
        return parent::beforeAction($action);
    }

    public function actionMyProfile()
    {
        $model = Member::findById(Yii::$app->user->id);
        $list_img = Image::find()->select('image')->asArray()->where(['member_id' => Yii::$app->user->id])->all();
        if ($model->load(Yii::$app->request->post(), "Member")) {
            $model->save(false);
        }
        return $this->render('my_profile', ['model' => $model, 'list_img' => $list_img, 'img_slides' => $this->img_slides]);
    }

    public function actionMemberProfile($member_id)
    {
        $model = Member::findById($member_id);
        $list_img = Image::find()->select('image')->asArray()->where(['member_id' => $member_id])->all();
        if (Yii::$app->user->can('editOwnProfile', ['member' => $model]))
            $this->redirect(['profile/my-profile']);
        if (Yii::$app->user->can('editProfile')) {
            if ($model->load(Yii::$app->request->post(), "Member")) {
                $model->save();
            }
            return $this->render('member_profile_admin', ['model' => $model, 'img_slides' => $this->img_slides, 'list_img' => $list_img]);
        }
        $data = Member::findById($member_id);
        return $this->render('member_profile', ['data' => $data, 'img_slides' => $this->img_slides, 'list_img' => $list_img]);
    }

}

views/member/list_member.php
<?php

use app\helpers\MyHelper;
use yii\widgets\LinkPager;
use yii\helpers\Url;
use yii\widgets\ActiveForm;


?>
<title><?= $title ?></title>
<div id="menu-1" class="about content">
    <div class="row">
        <ul class="tabs">
            <li class="col-md-3 col-sm-3">
                <a href=<?= Url::to(['/member/all-members']) ?> class="icon-item <?php if (Yii::$app->controller->action->id == 'all-members') echo 'active' ?>
                ">
                <b style="font-size:15px">All<br>Members</b>
                </a> <!-- /.icon-item -->
            </li>
            <li class="col-md-3 col-sm-3">
                <a href=<?= Url::to(['/member/older-members']) ?> class="icon-item <?php if (Yii::$app->controller->action->id == 'older-members') echo 'active' ?>
                ">
                <b style="font-size:15px">Older<br>Members</b>
                </a> <!-- /.icon-item -->
            </li>
            <li class="col-md-3 col-sm-3">
                <a href=<?= Url::to(['/member/members-of-the-same-age']) ?> class="icon-item <?php if (Yii::$app->controller->action->id == 'members-of-the-same-age') echo 'active' ?>
                ">
                <b style="font-size:15px">Members Of The Same Age</b>
                </a> <!-- /.icon-item -->
            </li>
            <li class="col-md-3 col-sm-3">
                <a href=<?= Url::to(['/member/younger-members']) ?> class="icon-item <?php if (Yii::$app->controller->action->id == 'younger-members') echo 'active' ?>
                ">
                <b style="font-size:15px">Younger<br>Members</b>
                </a> <!-- /.icon-item -->
            </li>
        </ul>



    </div>
    <!-- /.row -->
    <?php if (isset($find)): ?>
    <?php $form = ActiveForm::begin() ?>
    <div class="row">
        <div class="col-md-6 col-sm-6"></div>
        <div class="col-md-4 col-sm-4">
            <input name="find" placeholder="Find member...">
        </div>
        <div class="col-md-2 col-sm-2">
            <input type="submit" value="Find"></div>
    </div>
    <?php ActiveForm::end() ?>
</div>
<?php endif; ?>

<div class="row">

    <?php if (isset($members)) { ?>
        <?php foreach ($members as $member): ?>

            <div class="col-md-3 col-sm-3">
                <div class="member-item">
                    <div class="thumb">
                        <a href=<?= Url::to(['/profile/member-profile', 'member_id' => $member['id']]) ?>><img
                                src=<?php if(empty($member['avatar'])) echo Yii::getAlias('@web/web/images/base_avatar.jpg');
                            else echo Yii::getAlias('@web/web/img/'.$member['avatar']);
                            ?>></a>
                    </div>
                    <h4><?= $member['name'] ?></h4>
                    <span>Age: </span><?php if ($member['birthday']) echo MyHelper::getAge($member['birthday']); else echo NONE; ?>
                    <br>
                    <span>Phone Numbers: </span><?php if ($member['phone']) echo $member['phone']; else echo NONE; ?>
                </div>
                <!-- /.member-item -->
            </div>

        <?php endforeach; ?>
        <div class="col-md-12 col-sm-12"><?= LinkPager::widget(['pagination' => $pagination]) ?></div>
    <?php }  ?>

</div>
</div>
<div id="slideshowxx">
    <img class="activexx" src=<?= Yii::getAlias('@web/web/img/' . $img_slides[0]['image']) ?>>
    <?php for ($i = 1; $i < count($img_slides); $i++) { ?>
        <img src=<?= Yii::getAlias('@web/web/img/' . $img_slides[$i]['image']) ?>>
    <?php } ?>
</div>

<script type="text/javascript" src=<?= Yii::getAlias('@web/web/js/vendor/jquery-1.10.1.min.js') ?>></script>
<script type="text/javascript">

    function slideSwitch() {
        var $active = $('#slideshowxx IMG.activexx');

        if ($active.length == 0) $active = $('#slideshowxx IMG:last');

        // use this to pull the images in the order they appear in the markup
        var $next = $active.next().length ? $active.next()
            : $('#slideshowxx IMG:first');

// xóa ghi chú ở 3 dòng bên dưới nếu bạn muốn hiển thị ảnh ngẫu nhiên

        var $sibs = $active.siblings();
        var rndNum = Math.floor(Math.random() * $sibs.length);
        var $next = $($sibs[rndNum]);

        $active.addClass('last-activexx');

        $next.css({opacity: 0.0})
            .addClass('activexx')
            .animate({opacity: 1.0}, 1000, function () {
                $active.removeClass('activexx last-activexx');
            });
    }

    $(function () {
        setInterval("slideSwitch()", 10000);
    });

</script>
<style>
    #slideshowxx {
        position: relative;
        height: 350px;
        z-index: -1;
    }

    #slideshowxx IMG {
        position: absolute;
        top: 0;
        left: 0;
        z-index: 8;
        opacity: 0.0;
    }

    #slideshowxx IMG.activexx {
        z-index: 10;
        opacity: 1.0;
    }

    #slideshowxx IMG.last-activexx {
        z-index: 9;
    }

    #slideshowxx img {
        /* Set rules to fill background */
        min-height: 100%;
        min-width: 1024px;

        /* Set up proportionate scaling */
        width: 100%;
        height: auto;

        /* Set up positioning */
        position: fixed;
        top: 0;
        left: 0;
    }

</style>

views/member/login.php
<?php 
 	use yii\widgets\ActiveForm;
 	use yii\helpers\Html;

	$form = ActiveForm::begin();
	echo $form->field($model, 'username')->textInput();
	echo $form->field($model, 'password')->passwordInput();
	echo yii\authclient\widgets\AuthChoice::widget([
	     'baseAuthUrl' => ['member/auth'],
	     'popupMode' => false,
		]);
 ?>
<title>Login</title>
<div id="slideshowxx">
	<img class="activexx" src=<?= Yii::getAlias('@web/web/img/' . $img_slides[0]['image']) ?> />
	<?php for($i=1;$i<count($img_slides);$i++) { ?>
		<img src=<?= Yii::getAlias('@web/web/img/' . $img_slides[$i]['image']) ?> />
	<?php } ?>
</div>

<script type="text/javascript" src=<?= Yii::getAlias('@web/web/js/vendor/jquery-1.10.1.min.js') ?>></script>
<script type="text/javascript">

	function slideSwitch() {
		var $active = $('#slideshowxx IMG.activexx');

		if ($active.length == 0) $active = $('#slideshowxx IMG:last');

		// use this to pull the images in the order they appear in the markup
		var $next = $active.next().length ? $active.next()
			: $('#slideshowxx IMG:first');

// xóa ghi chú ở 3 dòng bên dưới nếu bạn muốn hiển thị ảnh ngẫu nhiên

		var $sibs = $active.siblings();
		var rndNum = Math.floor(Math.random() * $sibs.length);
		var $next = $($sibs[rndNum]);

		$active.addClass('last-activexx');

		$next.css({opacity: 0.0})
			.addClass('activexx')
			.animate({opacity: 1.0}, 1000, function () {
				$active.removeClass('activexx last-activexx');
			});
	}

	$(function () {
		setInterval("slideSwitch()", 10000);
	});

</script>
<style>
	#slideshowxx {
		position: relative;
		height: 350px;
		z-index: -1;
	}

	#slideshowxx IMG {
		position: absolute;
		top: 0;
		left: 0;
		z-index: 8;
		opacity: 0.0;
	}

	#slideshowxx IMG.activexx {
		z-index: 10;
		opacity: 1.0;
	}

	#slideshowxx IMG.last-activexx {
		z-index: 9;
	}

	#slideshowxx img {
		/* Set rules to fill background */
		min-height: 100%;
		min-width: 1024px;

		/* Set up proportionate scaling */
		width: 100%;
		height: auto;

		/* Set up positioning */
		position: fixed;
		top: 0;
		left: 0;
	}

</style>

views/member/upload.php
<?php
/**
 * Created by PhpStorm.
 * User: MINH
 * Date: 7/12/2016
 * Time: 10:07 AM
 */

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use karpoff\icrop\CropImageUpload;

?>

<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="upload_box">
            <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>
            <?= $form->field($model, 'name')->textInput(['placeholder' => 'Edit...']) ?>
            <?= $form->field($model, 'image')->fileInput()->widget(CropImageUpload::className(), ['options' => ['class' => 'btn btn-info']]) ?>
            <?= $form->field($model, 'is_avatar')->checkbox(['value'=>true]) ?>
            <?= Html::submitButton('Upload', ['class' => 'btn btn-primary']) ?>
            <?php ActiveForm::end() ?>
        </div>
    </div>
</div>
<div id="slideshowxx">
    <img class="activexx" src=<?= Yii::getAlias('@web/web/img/' . $img_slides[0]['image']) ?>>
    <?php for ($i = 1; $i < count($img_slides); $i++) { ?>
        <img src=<?= Yii::getAlias('@web/web/img/' . $img_slides[$i]['image']) ?>>
    <?php } ?>
</div>

<script type="text/javascript" src=<?= Yii::getAlias('@web/web/js/vendor/jquery-1.10.1.min.js') ?>></script>
<script type="text/javascript">

    function slideSwitch() {
        var $active = $('#slideshowxx IMG.activexx');

        if ($active.length == 0) $active = $('#slideshowxx IMG:last');

        // use this to pull the images in the order they appear in the markup
        var $next = $active.next().length ? $active.next()
            : $('#slideshowxx IMG:first');

// xóa ghi chú ở 3 dòng bên dưới nếu bạn muốn hiển thị ảnh ngẫu nhiên

        var $sibs = $active.siblings();
        var rndNum = Math.floor(Math.random() * $sibs.length);
        var $next = $($sibs[rndNum]);

        $active.addClass('last-activexx');

        $next.css({opacity: 0.0})
            .addClass('activexx')
            .animate({opacity: 1.0}, 1000, function () {
                $active.removeClass('activexx last-activexx');
            });
    }

    $(function () {
        setInterval("slideSwitch()", 10000);
    });

</script>
<style>
    #slideshowxx {
        position: relative;
        height: 350px;
        z-index: -1;
    }

    #slideshowxx IMG {
        position: absolute;
        top: 0;
        left: 0;
        z-index: 8;
        opacity: 0.0;
    }

    #slideshowxx IMG.activexx {
        z-index: 10;
        opacity: 1.0;
    }

    #slideshowxx IMG.last-activexx {
        z-index: 9;
    }

    #slideshowxx img {
        /* Set rules to fill background */
        min-height: 100%;
        min-width: 1024px;

        /* Set up proportionate scaling */
        width: 100%;
        height: auto;

        /* Set up positioning */
        position: fixed;
        top: 0;
        left: 0;
    }

</style>